---

- name: Test influxdb
  hosts: all
  become: yes
  roles:
    - ""
  vars_files:
    - "defaults/main.yml"
    - "vars/main.yml"
    - "vars/test.yml"
  tasks:
    - include: "tasks/main.yml"
  handlers:
    - include: "handlers/main.yml"
